    source 'https://rubygems.org'

    # Rails master
    gem 'rails', github: 'rails/rails', branch: '7-1-stable'

    # Rails last release
    # gem 'rails'

    gem 'sqlite3'
    gem 'ransack', github: 'activerecord-hackery/ransack'
