source 'https://rubygems.org'

gem 'jekyll', '~> 4.4'
gem 'just-the-docs', '~> 0.12'
gem 'jekyll-relative-links'
gem 'jekyll-redirect-from'
gem 'jekyll-seo-tag'
# `jekyll serve` needs WEBrick, which Ruby 3.0+ no longer bundles.
gem 'webrick'

group :test do
  gem 'html-proofer'
end
