source 'https://rubygems.org'

gem 'jekyll', '~> 4.4'
gem 'just-the-docs', '~> 0.12'
gem 'jekyll-relative-links'
gem 'jekyll-redirect-from'
gem 'jekyll-seo-tag'

group :test do
  gem 'html-proofer'
end
